-- MySQL Script generated by MySQL Workbench
-- Mon Dec 19 09:11:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`AperturaProgramatica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AperturaProgramatica` (
  `IdAperturaProgramatica` VARCHAR(12) NOT NULL,
  `NombreAperturaProgramatica` VARCHAR(90) NOT NULL,
  `PresupuestoVigente` DOUBLE NOT NULL,
  PRIMARY KEY (`IdAperturaProgramatica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proyecto` (
  `IdProyecto` INT NOT NULL,
  `NombreProyecto` VARCHAR(90) NOT NULL,
  `Distrito` VARCHAR(1) NOT NULL,
  `OTB` VARCHAR(45) NOT NULL,
  `PrecioReferencialProyecto` DOUBLE NOT NULL,
  `ResponsableProyecto` VARCHAR(60) NULL,
  `PresupuestoProyecto` DOUBLE NOT NULL,
  `InicioProcesoContratacion` DATE NULL,
  `Etapa` VARCHAR(45) NOT NULL,
  `FechaFinPlazo` DATE NULL,
  `CodigoSISINWEB` INT NOT NULL,
  `Estado` TINYINT(1) NOT NULL DEFAULT '1',
  `ModalidadContratacion` VARCHAR(45) NULL,
  `Adjudicatario` VARCHAR(45) NULL,
  `Supervisor` VARCHAR(45) NOT NULL,
  `FechaOrdenProceder` DATE NULL,
  `AperturaProgramatica_IdAperturaProgramatica` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`IdProyecto`),
  INDEX `fk_Proyecto_AperturaProgramatica1_idx` (`AperturaProgramatica_IdAperturaProgramatica` ASC),
  CONSTRAINT `fk_Proyecto_AperturaProgramatica1`
    FOREIGN KEY (`AperturaProgramatica_IdAperturaProgramatica`)
    REFERENCES `mydb`.`AperturaProgramatica` (`IdAperturaProgramatica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reformulado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reformulado` (
  `IdReformulado` INT NOT NULL,
  `FechaAprobacion` DATE NOT NULL,
  `FechaInicio` DATE NOT NULL,
  `LeyResolucion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdReformulado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EvaluacionFisicaFinanciera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EvaluacionFisicaFinanciera` (
  `FechaCorte` DATE NOT NULL,
  `PresupuestoPreventivo` DOUBLE NOT NULL,
  `PresupuestoPagado` DOUBLE NOT NULL,
  `Saldo` DOUBLE NOT NULL,
  `PorcentajeEjecucionFisico` INT NOT NULL,
  `PorcentajeEjecucionFinanciera` INT NOT NULL,
  PRIMARY KEY (`FechaCorte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `IdUsuario` INT NOT NULL,
  `NombreUsuario` VARCHAR(60) NOT NULL,
  `CargoUsuario` VARCHAR(45) NOT NULL,
  `Oficina` VARCHAR(45) NOT NULL,
  `TipoUsuario` TINYINT(1) NOT NULL DEFAULT '1',
  `UsuarioLog` VARCHAR(10) NOT NULL,
  `ContrasenaLog` VARCHAR(10) NOT NULL,
  `EstadoUsuario` TINYINT(1) NOT NULL DEFAULT 1,
  `FechaRegistroUsuario` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`IdUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Avance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avance` (
  `FechaAvance` DATE NOT NULL,
  `DescripcionAvance` VARCHAR(90) NOT NULL,
  `PorcentajeAvance` INT NOT NULL,
  `Formulario` VARCHAR(15) NULL,
  `Observaciones` VARCHAR(120) NOT NULL,
  `Pendiente` VARCHAR(120) NOT NULL,
  `AsignadoEn` VARCHAR(45) NOT NULL,
  `AsignadoCon` VARCHAR(60) NOT NULL,
  `HojaRuta` VARCHAR(9) NOT NULL,
  `MontoCertificado` DOUBLE NOT NULL,
  `Proyecto_IdProyecto` INT NOT NULL,
  `Responsable_IdResponsable1` INT NOT NULL,
  PRIMARY KEY (`FechaAvance`),
  INDEX `fk_Avance_Proyecto1_idx` (`Proyecto_IdProyecto` ASC),
  INDEX `fk_Avance_Responsable1_idx` (`Responsable_IdResponsable1` ASC),
  CONSTRAINT `fk_Avance_Proyecto1`
    FOREIGN KEY (`Proyecto_IdProyecto`)
    REFERENCES `mydb`.`Proyecto` (`IdProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avance_Responsable1`
    FOREIGN KEY (`Responsable_IdResponsable1`)
    REFERENCES `mydb`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reformulado_has_AperturaProgramatica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reformulado_has_AperturaProgramatica` (
  `Reformulado_IdReformulado` INT NOT NULL,
  `AperturaProgramatica_IdAperturaProgramatica` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`Reformulado_IdReformulado`, `AperturaProgramatica_IdAperturaProgramatica`),
  INDEX `fk_Reformulado_has_AperturaProgramatica_AperturaProgramatic_idx` (`AperturaProgramatica_IdAperturaProgramatica` ASC),
  INDEX `fk_Reformulado_has_AperturaProgramatica_Reformulado1_idx` (`Reformulado_IdReformulado` ASC),
  CONSTRAINT `fk_Reformulado_has_AperturaProgramatica_Reformulado1`
    FOREIGN KEY (`Reformulado_IdReformulado`)
    REFERENCES `mydb`.`Reformulado` (`IdReformulado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reformulado_has_AperturaProgramatica_AperturaProgramatica1`
    FOREIGN KEY (`AperturaProgramatica_IdAperturaProgramatica`)
    REFERENCES `mydb`.`AperturaProgramatica` (`IdAperturaProgramatica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AperturaProgramatica_has_EvaluacionFisicaFinanciera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AperturaProgramatica_has_EvaluacionFisicaFinanciera` (
  `AperturaProgramatica_IdAperturaProgramatica` VARCHAR(12) NOT NULL,
  `EvaluacionFisicaFinanciera_FechaCorte` DATE NOT NULL,
  PRIMARY KEY (`AperturaProgramatica_IdAperturaProgramatica`, `EvaluacionFisicaFinanciera_FechaCorte`),
  INDEX `fk_AperturaProgramatica_has_EvaluacionFisicaFinanciera_Eval_idx` (`EvaluacionFisicaFinanciera_FechaCorte` ASC),
  INDEX `fk_AperturaProgramatica_has_EvaluacionFisicaFinanciera_Aper_idx` (`AperturaProgramatica_IdAperturaProgramatica` ASC),
  CONSTRAINT `fk_AperturaProgramatica_has_EvaluacionFisicaFinanciera_Apertu1`
    FOREIGN KEY (`AperturaProgramatica_IdAperturaProgramatica`)
    REFERENCES `mydb`.`AperturaProgramatica` (`IdAperturaProgramatica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AperturaProgramatica_has_EvaluacionFisicaFinanciera_Evalua1`
    FOREIGN KEY (`EvaluacionFisicaFinanciera_FechaCorte`)
    REFERENCES `mydb`.`EvaluacionFisicaFinanciera` (`FechaCorte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
